name: Firmware
on: [push, pull_request]

jobs:
  firmware-build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        target-board:
        - 'cynthion'
        - 'cynthion_d11'
        - 'cynthion_d21'
        - 'samd11_xplained'
        - 'qtpy'
        - 'raspberry_pi_pico'
        - 'waveshare_rp2040_zero'
        - 'adafruit_qtpy_rp2040'
    steps:
    - name: Checkout source code
      uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v25
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - uses: cachix/cachix-action@v14
      with:
        name: apollo-firmware
        # If you chose API tokens for write access OR if you have a private cache
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - name: ❄️ Build Apollo firmware for ${{ matrix.target-board }}
      run: |
        nix-build -A apollo-firmware-${{ matrix.target-board }}
    - name: 📦 Upload binary
      uses: actions/upload-artifact@v3
      with:
        name: apollo-firmware-${{ matrix.target-board }}
        path: result/*
